name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: npm install -g yalc
    - name: yarn link
      run: |
        yarn install
        yalc publish
        cd examples/simple
        yalc add @zefiros/npm-defaults
        yarn install
        yarn build
        yarn test
      env:
        CI: true
