name: Publish
on: push
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
    # - name: Cancel if not a release publish
    #   run: exit 1
    #   if: github.event.action != 'created'
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - run: |
        echo "registry=https://npm.pkg.github.com/" > ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
        yarn publish --tag next --access public
      env:
        NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}