name: Publish
on: push
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
    # - name: Cancel if not a release publish
    #   run: exit 1
    #   if: github.event.action != 'created'
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - run: |
        echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >>~/.yarnrc
        yarn publish --tag next --access public