name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Use Node.js 14
        uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Get npm cache directory path
        id: npm-cache-dir
        run: |
          echo "::set-output name=cache_dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.cache_dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install -g npm@7 yalc
      - name: npm build
        run: |
          npm install

          # initialize environment
          ./bin/run env --install

          # for using named modules
          npm link

          npm-defaults ci

          yalc publish
      - name: library - yarn install, build, and test
        working-directory: ./examples/library
        run: |
          yalc add @zefiros/npm-defaults
          ../../bin/run ci
      - name: yargs-cli - yarn install, build, and test
        working-directory: ./examples/yargs-cli
        run: |
          yalc add @zefiros/npm-defaults
          ../../bin/run ci
      - name: coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: release
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master'
        run: |
          ./bin/run release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: create pull request
        if: github.ref == 'refs/heads/development'
        run: ./bin/run make-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
