name: Node CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Use Node.js 10
      uses: actions/setup-node@master
      with:
        node-version: 10
    - run: npm install -g yarn yalc codecov
    - name: yarn link
      run: |
        yarn install
        yalc publish
      env:
        CI: true
    - name: yarn install, build, and test
      working-directory: examples/simple
      run: |
        yalc add @zefiros/npm-defaults
        yarn install
        yarn lint
        yarn build
        yarn test
      env:
        CI: true
    - name: coverage
      run: codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    - name: release
      if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master'
      run: |
        export GIT_AUTHOR_NAME=Hoid
        export GIT_COMMITTER_NAME=Hoid
        export GIT_AUTHOR_EMAIL=hoid@zefiros.io
        export GIT_COMMITTER_EMAIL=hoid@zefiros.io
        yarn release
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: create pull request
      if: github.ref == 'refs/heads/development'
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "development"                
        destination_branch: "master"  
        pr_title: "Create new release"
        pr_body: ":crown: *An automated PR*"
        github_token: ${{ secrets.GITHUB_TOKEN }}