name: Node CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Use Node.js 10
      uses: actions/setup-node@master
      with:
        node-version: 10
    - run: npm install -g yarn yalc codecov
    - name: yarn link
      run: |
        export PATH="$(yarn global bin):$PATH"
        yarn install
        ./bin/run ci
        yalc publish
        yarn link
        yarn global add @zefiros/npm-defaults
      env:
        CI: true
    - name: yarn install, build, and test
      working-directory: examples/library
      run: |
        yalc add @zefiros/npm-defaults --pure
        npm-defaults ci
      env:
        CI: true
    - name: coverage
      run: codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    - name: release
      if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master'
      run: |
         npm-defaults release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: create pull request
      if: github.ref == 'refs/heads/development'
      run: npm-defaults make-release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}