name: Node CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Use Node.js 10
      uses: actions/setup-node@master
      with:
        node-version: 10
    - run: npm install -g yarn yalc codecov
    - name: yarn link
      run: |
        export PATH="$(yarn global bin):$PATH"
        yarn install
        ./bin/run ci
        yalc publish
    - name: library - yarn install, build, and test
      working-directory: examples/library
      run: |
        yalc add @zefiros/npm-defaults
        ../../bin/run ci
    - name: oclif-cli - yarn install, build, and test
      working-directory: examples/oclif-cli
      run: |
        yalc add @zefiros/npm-defaults
        ../../bin/run ci
    - name: coverage
      run: codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    - name: release
      if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master'
      run: |
         ./bin/run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: create pull request
      if: github.ref == 'refs/heads/development'
      run: ./bin/run make-release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}